name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 * * * *' # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly
permissions:
  contents: write # To write the generated contents to the readme

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Pull in medium posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          remove_duplicates: true
          feed_list: "https://medium.com/feed/@rizwan3d"
          committer_email: "allgame45@hotmail.com"
          date_format: "mmm d, yyyy"
      - name: Pull in youtube videos
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UCSQJpRcHLSVE1CpwMJ0xmew"
          custom_tags: "channelId/yt:channelId/,videoId/yt:videoId/"
          date_format: "mmm d, yyyy"
          template: '<a href="$url">$title - $date </a> $newline'
          committer_email: "allgame45@hotmail.com"
          
