name: Waka Readme Stats

on:
  schedule: # Run workflow automatically
    - cron: '30 18 * * *'
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly
permissions:
  contents: write # To write the generated contents to the readme

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_PROJECTS: "False"
          SHOW_TIMEZONE: "False"
          SHOW_LOC_CHART: "False"
          SHOW_LINES_OF_CODE: "False"
          SHOW_PROFILE_VIEWS: "False"
